### ISSUE TITLE
Convert templates to JSX

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-hotgraphic#248]
Convert hotgraphic.hbs and hotgraphicPopup.hbs to JSX templates.

**Comment by chris-steele** [comment]
@swashbuck I see you assigned and then unassigned; do you want me to pick this up?

**Comment by swashbuck** [comment]
@chris-steele I believe I had closed it because there were a few other issues that sounded like they needed to be addressed first (ex. #243 ).  Feel free to pick this ticket up, though.  Not sure how urgent those other issues are.

**Comment by chris-steele** [comment]
@swashbuck  if/when the PR for #243 is merged I'll pick this up

**Comment by chris-steele** [comment]
@swashbuck as you probably know #243 was merged. I was wondering, since you've been working on similar plugins do you want to take the reins back on this issue and perhaps also https://github.com/adaptlearning/adapt-contrib-narrative/issues/238? I spoke with @kirsty-hames who is happy for someone else to take it on.

**Comment by swashbuck** [comment]
@chris-steele Sure, happy to take this one on, along with Narrative.
