### ISSUE TITLE
Error when using _isNarrativeOnMobile

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-hotgraphic#278]
### Subject of the issue
When using `_isNarrativeOnMobile: true` and viewing on mobile, the following error is shown:

```
Uncaught (in promise) TypeError: parentChildViews is undefined
    replaceWithNarrative hotgraphicView.js:47
```

Note that this does not happen if _first_ viewing on desktop and then _switching_ to mobile. It only happens if you are viewing mobile when the page _first loads_.

### Your environment
* Framework 5.31.11
* Hot Graphic 6.7.5
* Narrative 7.4.9

### Steps to reproduce
1. Using a desktop browser, adjust screen width to mobile view (719px or narrower, assuming screenSize properties are default)
2. In a Hot Graphic, enable `_isNarrativeOnMobile`
3. Reload the page

### Expected behaviour
No console errors

### Actual behaviour
Console error!

### Screenshots
<img width="429" alt="Screenshot 2023-06-29 at 3 18 03 PM" src="https://github.com/adaptlearning/adapt-contrib-hotgraphic/assets/898168/75b408c0-e2e0-4e1f-8b22-99b3f2ed52fc">

**Comment by swashbuck** [comment]
Hi @oliverfoster . In the Hot Graphic view, I can prevent the error by changing this line:

https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/a4b949eeeccbecac74f188462d8af6b068626d5a/js/hotgraphicView.js#L46

To return an empty array:

```
const parentChildViews = parentView.getChildViews() || [];
```

However, I noticed that `getChildViews()` in _adaptView.js_ will return "undefined" if `_childViews` is not set. Should it return an empty array instead?

https://github.com/adaptlearning/adapt-contrib-core/blob/1e73f329c21e6eb906c102db23f600666117cd74/js/views/adaptView.js#L397

Is there a better way to handle this in general (ex. changing something in `adapt-contrib-narrative`)?

**Comment by kirsty-hames** [comment]
I can also replicate this issue testing on Mac Safari, Chrome and FF. Same conditions, open the browser at mobile screen width and increase the browser width above 719px.

In addition to the console error, multiple instances of Hotgraphic are rendered. The first instance of Hotgraphic displays the narrative slides rather than an image with pins.
<img width="279" alt="multiple_instances_error" src="https://github.com/adaptlearning/adapt-contrib-hotgraphic/assets/7045330/3c973a98-6c3f-40fa-a0ed-3e6d4c66926e">
