### ISSUE TITLE
hide pins

### ISSUE THREAD

**Issue by sandervanzijl** [adaptlearning/adapt-contrib-hotgraphic#94]
as a feature request: could someone add the possibility to add a hotspot, without placing a pin on top of it.

this way I could use a maingraphic that already has areas on it and instruct the learners to click the areas, in stead of clicking the pins.

**Comment by markl55** [comment]
Hi Sander,

Following on from the conversation in the forum this feature exists using the "Use as graphics pins" should be "false".

If you are happy with that would you mind replying so that we can close this issue?

Thanks,

Mark.

**Comment by sandervanzijl** [comment]
this is not what I mean. I want normal hotspot, but without seeing the pins. or better, with the possibility to change the pins graphic.

**Comment by ciaranlp** [comment]
Hey sander, the pin icon is set in the less,

the pin icon is set by the `.hotgraphic-graphic-pin-icon:before` `content: "\e60f";` this can be changed to any of the other icons included in the vanilla font.

Otherwise to hide the pin completely but still clickable you can set the `.hotgraphic-graphic-pin-icon` to`visibility: hidden;` **NOTE NOT** `display: none;` as the parent div requires this content for its height and width dimensions, then set the `.hotgraphic-graphic-pin` to `background-color: transparent;`

Hope that helps 

Ciaran

**Comment by guywillis** [comment]
This issue was moved to adaptlearning/adapt_framework#849
